apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-ca
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Macsok/homeLAB.git
    targetRevision: main
    path: gitOps/infra/homelab-ca

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true